extends: airbnb

plugins:
  - react
  - jsx-a11y
  - import

rules:
  import/no-extraneous-dependencies: 
    - "error"
    - devDependencies: 
      - "**/test/**/*-test.js"
      - "**/gulpfile.babel.js"
  comma-dangle:
    - "error"
    -        
      arrays: "never"
      objects: "always"
      imports: "never"
      exports: "never"
      functions: "ignore"

env:
  node: true
  mocha: true
