verbose: false  
instrumentation:
    excludes: ['gulpfile.babel.js', 'dist/**/*']
    include-all-sources: true
reporting:
    print: both
check:
    global:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
    each:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
